Used contentUTF8 in FeignExceptionLogger
hmcts/bulk-scan-orchestrator pull request #1188
Opened 2020-09-03 14:52 UTC by apereverzin

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/BPS-1209

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-09-03 14:57 UTC, doncem approved these changes

2020-09-03 15:54 UTC, apereverzin commented on src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/logging/FeignExceptionLogger.java
> +            exception.responseBody().map(b -> exception.contentUTF8()).orElseGet(exception::getMessage)
`contentUTF8()` uses responseBody internally

2020-09-03 17:42 UTC, doncem commented on src/main/java/uk/gov/hmcts/reform/bulkscan/orchestrator/logging/FeignExceptionLogger.java
> +            exception.responseBody().map(b -> exception.contentUTF8()).orElseGet(exception::getMessage)
iirc, `responseBody` returns optional whereas `contentUTF8` uses `responseBody` but throws exception if empty, hence such _map or else_ approach ;)

2020-09-04 10:25 UTC, rkondratowicz commented on src/test/java/uk/gov/hmcts/reform/bulkscan/orchestrator/logging/FeignExceptionLoggerTest.java
> -        verify(exception, never()).getMessage();
test name no longer matches what's being tested

2020-09-04 10:26 UTC, rkondratowicz requested changes
error

2020-09-04 10:27 UTC, rkondratowicz approved these changes

2020-09-04 11:52 UTC, apereverzin commented
Consistently failing in Jenkins

2020-09-04 11:52 UTC, closed without merging